<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_series1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
lst = [ 1,2,3,4]
print(lst)


[1, 2, 3, 4]


In [21]:
print( '1d array')
a=np.array([1,2,4,5])
print(a)

1d array
[1 2 4 5]


In [18]:
print( '2d array')
b= np.array([[1,23,34,5],[1,2,3,4]])
print(b)

2d array
[[ 1 23 34  5]
 [ 1  2  3  4]]


In [17]:
print( '3d array')
c= np.array([[1,23,34,5],[1,2,3,4],[5,6,7,8]])
print(c)

3d array
[[ 1 23 34  5]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
type(a)


numpy.ndarray

## size = tells the number of elements in an array
arr.size


In [22]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


# shape =(rows,col)

In [24]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(3, 4)


## dtype = type of data present in that array

## arr.dtype

In [29]:
d=np.array([[1,2,4.2,5],[1,23,34,5],[1,2,3,4],[5,6,7,8]])

print(d)
print(d.shape)
print(d.dtype)

[[ 1.   2.   4.2  5. ]
 [ 1.  23.  34.   5. ]
 [ 1.   2.   3.   4. ]
 [ 5.   6.   7.   8. ]]
(4, 4)
float64


In [32]:
print(d.transpose())

[[ 1.   1.   1.   5. ]
 [ 2.  23.   2.   6. ]
 [ 4.2 34.   3.   7. ]
 [ 5.   5.   4.   8. ]]
