<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_series7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY RANDOM OPERATIONS**

In [ ]:
import numpy as np

In [ ]:
np.random.random(1)

array([0.67639532])

In [ ]:
np.random.random((1,1))

array([0.62416552])

In [ ]:
np.random.random((2,4))

array([[0.18958683, 0.58455316, 0.62332745, 0.96692456],
       [0.474871  , 0.91549819, 0.5736529 , 0.77100605]])

In [ ]:
np.random.random((3,3))

array([[0.52876453, 0.80260646, 0.94147047],
       [0.35882665, 0.88597446, 0.21425611],
       [0.36838303, 0.07925554, 0.15240272]])

In [ ]:
np.random.randint(1,10) #we get a random integer with in the given values


4

In [ ]:
np.random.randint(1,10,(2,2)) #we get a random integer with in the given values and the (2,2) represent the size of that array

array([[3, 5],
       [6, 5]])

In [ ]:
np.random.randint(1,10,(3,3)) # represent 3by3 array

array([[6, 5, 2],
       [1, 3, 7],
       [8, 1, 1]])

In [ ]:
np.random.randint(1,10,(3,1,1)) #represent random integer & the (3,3,3) is((no.of arrays),(no.of rows),(no.of coloumns))

array([[[7]],

       [[1]],

       [[3]]])

In [ ]:
np.random.rand(3,3) #represent random float & the (3,3) is the size of that array

array([[0.35255665, 0.3779548 , 0.03875768],
       [0.83541542, 0.51541124, 0.68289646],
       [0.76318949, 0.25911729, 0.47475933]])

In [ ]:
np.random.randn(3,3) #represent random negative float val  & the (3,3) is the size of that array

array([[ 0.23075685, -0.01426503, -0.49484403],
       [ 0.14680015, -1.32470378, -0.12517629],
       [ 1.92684588,  0.83422882, -0.89100301]])

In [ ]:
a=np.arange(1,11,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.random.choice(a))

4
