<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_series2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np


np.empty((rows,cols),dtype)

In [ ]:
np.empty((4,4),dtype=int)

array([[   816478934,            0, 489626271861, 433791696995],
       [498216206368, 468151435365, 476741369968, 416611827826],
       [450971566194, 519691042924, 502511173664, 416611827822],
       [416611827830, 463856468073, 420906795105, 433791697004]])

In [ ]:
np.empty((4,4),dtype= float)

array([[4.03835386e-315, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

np.ones((rows,cols),dtype)


In [ ]:
np.ones((4,4),dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.ones((4,4),dtype= float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((4,),dtype= float)


array([1., 1., 1., 1.])

In [ ]:
np.ones((4),dtype= float)


array([1., 1., 1., 1.])

In [ ]:
x= np.ones((4),dtype= float)
x

array([1., 1., 1., 1.])

In [22]:
x= np.ones((4),dtype= bool)
x

array([ True,  True,  True,  True])

In [24]:
x= np.ones((4),dtype= str)
x

array(['1', '1', '1', '1'], dtype='<U1')

In [9]:
y=np.ones(4)
y

array([1., 1., 1., 1.])

np.zeros((rows,cols),dtype)

In [18]:
z=np.zeros((4,8), dtype= int)
print(z)




[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [14]:
np.zeros((4,8), dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((4,8), dtype=bool)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [26]:
np.zeros((4,8), dtype=str)

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')