<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_problems_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creates a 3x4 empty array using np.empty().


In [5]:
import numpy as np

In [6]:
empArr = np.empty((3, 4))
print(empArr)

[[5.01204940e-315 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


# Creates a 3x4 array filled with the value 5 using np.full().

In [7]:
fullArr = np.full((3, 4), 5)
print(fullArr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]



# Using NumPy Sliding Window Comparison

## To count how many times that sequence appears horizontally inside the array

In [8]:
arr = np.array([[2, 8, 9, 4],
                [9, 4, 9, 4],
                [4, 5, 9, 7],
                [2, 9, 4, 3]])

seq = np.array([9, 4])
k = seq.size

sl = np.lib.stride_tricks.sliding_window_view(arr, k, axis=1)
out = np.sum(np.all(sl == seq, axis=2))
print(out)

4


# Using String Conversion and Count


In [9]:
#This method converts the entire array into a string and checks how many times the sequence pattern appears inside that string.

arr = np.array([[2, 8, 9, 4],

                [9, 4, 9, 4],

                [4, 5, 9, 7],

                [2, 9, 4, 3]])
out = repr(arr).count("9, 4")
print(out)

4


# Using Row-wise Conversion and Counting

In [10]:
#To converts each row into a string individually and searches for the sequence inside each row string.

arr = np.array([[2, 8, 9, 4],

                [9, 4, 9, 4],

                [4, 5, 9, 7],

                [2, 9, 4, 3]])
seq = "9 4"
out = sum(" ".join(map(str, r)).count(seq) for r in arr)
print(out)

4


# Using NumPy Equality Check with Shifted Arrays

In [11]:
arr = np.array([[2, 8, 9, 4],
                [9, 4, 9, 4],
                [4, 5, 9, 7],
                [2, 9, 4, 3]])

seq = np.array([9, 4])
a = arr[:, :-1]
b = arr[:, 1:]
out = np.sum((a == seq[0]) & (b == seq[1]))
print(out)

4
