<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_series5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY MATHEMATICAL OPERATIONS**

In [ ]:
import  numpy as np

###ADD - arr.add(arr1,arr2) // arr1+arr2

###SUB - arr.subtract(arr1,arr2) / arr1-arr2

###MULTIPLY - arr.multiply(arr1,arr2) // arr1*arr2

###DIVIDE - arr.divide(arr1,arr2) // arr1/rr2

### MATRIX MULTIPLICATION - a@b  ; DOT MULTIPLICATON - arr1.dot(arr2)



In [ ]:
a=np.arange(0,18).reshape(6,3)
b=np.arange(20,38).reshape(6,3)
c=np.arange(40,58).reshape(6,3)

print(a)
print(b)
print(c)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]
[[40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]]


In [ ]:
a+b+c

array([[ 60,  63,  66],
       [ 69,  72,  75],
       [ 78,  81,  84],
       [ 87,  90,  93],
       [ 96,  99, 102],
       [105, 108, 111]])

In [ ]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [ ]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [ ]:
print(a)
print(b)
np.subtract(a,b)
a-b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [ ]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [ ]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [ ]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [ ]:
b/a

/tmp/ipython-input-2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([[        inf, 21.        , 11.        ],
       [ 7.66666667,  6.        ,  5.        ],
       [ 4.33333333,  3.85714286,  3.5       ],
       [ 3.22222222,  3.        ,  2.81818182],
       [ 2.66666667,  2.53846154,  2.42857143],
       [ 2.33333333,  2.25      ,  2.17647059]])

In [ ]:
b=b.reshape(3,6)
b

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37]])

In [ ]:
print(a.shape)
print(b.shape)

(6, 3)
(3, 6)


In [ ]:
a@b #matrix multiplication.

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [ ]:
a.dot(b) #dot multiplication.

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

### arr1.max()  -       gives the MAX element in that array1

###      arr1.aargmax() - gives  the index of the max element.

###  arr1.min()   -      gives the MIN element in that array1

###      arr1.aargmax() - gives  the index of the max element.





In [ ]:
print(a.max())
print(a.argmax())
print(b.max())
print(b.argmax())

17
17
37
17


# arr.sum(arr1) - gives the sum of that array1 values  
OR
# arr1.sum()

In [ ]:
print(a.sum())
print(np.sum(a))

print(b.sum())
print(np.sum(b))

print(c.sum())
print(np.sum(c))


153
153
513
513
873
873


## arr.sum(arr1, axis = 1) - gives the sum of values present in all rows in that array1 values, { 1 means ROWS}

## arr.sum(arr1, axis = 0) - gives the sum of values present in all coloumns in that array1 values, { 0 means COLOUMNS}


In [ ]:
print(a)
print(np.sum(a,axis=1))
a.sum(axis=1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[ 3 12 21 30 39 48]


array([ 3, 12, 21, 30, 39, 48])

In [ ]:
print(a)
print(np.sum(a,axis=0))
a.sum(axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[45 51 57]


array([45, 51, 57])

## arr.mean(a)- gives the mean of the that array1  

OR

## arr1.mean()- gives the mean of the that array1

In [ ]:
print(a.mean())
print(np.mean(a))

8.5
8.5


arr1.mean( axis = 1) - gives the mean of all rows in that array1,

 { 1 means ROWS}

OR

arr.mean(arr1, axis = 1) - gives the mean of all rows in that array1 ,

 { 1 means ROWS}

.

arr1.mean(axis = 0) - gives the mean of  all coloumns in that array1,

 { 0 means COLOUMNS}

 OR

arr.mean(arr1, axis = 0) - gives the mean of all coloumns in that array1,

 { 0 means COLOUMNS}

---





In [ ]:
print(a.mean(axis=1))
print(a.mean(axis=0))

[ 1.  4.  7. 10. 13. 16.]
[7.5 8.5 9.5]


# arr.sqrt(arr1)- gives the square root of each and every element in that array1


In [ ]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563]])

# arr.std(arr1)- gives the sstandard deviation of that array1


In [ ]:
print(np.std(a))
print(np.std(a, axis=1)) #each and every row
print(np.std(a, axis=0)) #each and every coloumn

5.188127472091127
[0.81649658 0.81649658 0.81649658 0.81649658 0.81649658 0.81649658]
[5.12347538 5.12347538 5.12347538]


arr.log(arr1)- gives the logarithm of that array1

In [ ]:
print(a)
print(np.log(a))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[      -inf 0.         0.69314718]
 [1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527]
 [2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]]


/tmp/ipython-input-149375448.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))
