<a href="https://colab.research.google.com/github/pradeekamanickam/python/blob/main/numpy_problem_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating a 2D Pattern Matrix

Problem: Create a 5x5 matrix filled with 1s on the border (first row, last row, first column, last column) and 0s on the inside.

In [1]:
import numpy as np

# Create a 5x5 matrix of ones
matrix = np.ones((5, 5))

# Set the inner part (rows 1-3, cols 1-3) to zero
matrix[1:-1, 1:-1] = 0

print("Bordered Matrix:\n", matrix)


Bordered Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
